spring:
  docker:
    compose:
      enabled: true
      file: docker-compose.yml

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG